# 210968090_Santhosh_Darla_IDA_Week-7

In [30]:
pip install --user mlxtend

Requirement already satisfied: mlxtend in c:\users\asus\appdata\roaming\python\python38\site-packages (0.21.0)
Requirement already satisfied: numpy>=1.16.2 in c:\users\asus\anaconda3\lib\site-packages (from mlxtend) (1.18.5)
Requirement already satisfied: setuptools in c:\users\asus\anaconda3\lib\site-packages (from mlxtend) (49.2.0.post20200714)
Requirement already satisfied: pandas>=0.24.2 in c:\users\asus\anaconda3\lib\site-packages (from mlxtend) (1.0.5)
Requirement already satisfied: joblib>=0.13.2 in c:\users\asus\anaconda3\lib\site-packages (from mlxtend) (0.16.0)
Requirement already satisfied: scipy>=1.2.1 in c:\users\asus\anaconda3\lib\site-packages (from mlxtend) (1.5.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\asus\anaconda3\lib\site-packages (from mlxtend) (3.2.2)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\asus\appdata\roaming\python\python38\site-packages (from mlxtend) (1.1.2)
Requirement already satisfied: pytz>=2017.2 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2020.1)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\asus\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.1.0)
Requirement already satisfied: six>=1.5 in c:\users\asus\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas>=0.24.2->mlxtend) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:
import pandas as pd
import mlxtend
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [18]:
df=pd.read_csv("groceries.csv",sep=';',header=None)
df

                                                      0
0     citrus fruit,semi-finished bread,margarine,rea...
1                          tropical fruit,yogurt,coffee
2                                            whole milk
3           pip fruit,yogurt,cream cheese ,meat spreads
4     other vegetables,whole milk,condensed milk,lon...
...                                                 ...
9830  sausage,chicken,beef,hamburger meat,citrus fru...
9831                                  cooking chocolate
9832  chicken,citrus fruit,other vegetables,butter,y...
9833  semi-finished bread,bottled water,soda,bottled...
9834  chicken,tropical fruit,other vegetables,vinega...

[9835 rows x 1 columns]

## 2. How many transactions and items are there in the data set?

In [19]:
df.index.stop

9835

In [20]:
df[0].str.split().append

<bound method Series.append of 0       [citrus, fruit,semi-finished, bread,margarine,...
1                         [tropical, fruit,yogurt,coffee]
2                                           [whole, milk]
3       [pip, fruit,yogurt,cream, cheese, ,meat, spreads]
4       [other, vegetables,whole, milk,condensed, milk...
                              ...
9830    [sausage,chicken,beef,hamburger, meat,citrus, ...
9831                                 [cooking, chocolate]
9832    [chicken,citrus, fruit,other, vegetables,butte...
9833    [semi-finished, bread,bottled, water,soda,bott...
9834    [chicken,tropical, fruit,other, vegetables,vin...
Name: 0, Length: 9835, dtype: object>

In [21]:
groceries = []
with open('groceries.csv', 'r') as read_obj:
    csv_reader = reader(read_obj)
    for row in csv_reader:
        groceries.append(row)

In [22]:
encoder = TransactionEncoder()
transactions = encoder.fit(groceries).transform(groceries)

In [23]:
transactions = transactions.astype('int')

df = pd.DataFrame(transactions, columns=encoder.columns_)

df.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [24]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 
frequent_itemsets = apriori(df, min_support=0.02, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

      support                                         itemsets  length
0    0.033452                                       (UHT-milk)       1
1    0.052466                                           (beef)       1
2    0.033249                                        (berries)       1
3    0.026029                                      (beverages)       1
4    0.080529                                   (bottled beer)       1
..        ...                                              ...     ...
117  0.032232                 (whipped/sour cream, whole milk)       2
118  0.020742                     (whipped/sour cream, yogurt)       2
119  0.056024                             (yogurt, whole milk)       2
120  0.023183  (root vegetables, other vegetables, whole milk)       3
121  0.022267           (yogurt, whole milk, other vegetables)       3

[122 rows x 3 columns]

## 5. Find top selling items with minimum support of 2%?

In [25]:
frequent_itemsets = frequent_itemsets.sort_values(by='support', ascending=False)


frequent_itemsets[ (frequent_itemsets['length'] == 1) &
                   (frequent_itemsets['support'] >= 0.02) ][0:5]

     support            itemsets  length
57  0.255516        (whole milk)       1
39  0.193493  (other vegetables)       1
43  0.183935        (rolls/buns)       1
49  0.174377              (soda)       1
58  0.139502            (yogurt)       1

## 6. Find all frequent itemsets with minimum support of 5%?

In [26]:

frequent_itemsets[(frequent_itemsets['length'] > 1) & 
                  (frequent_itemsets['support'] >= 0.05)]

      support                        itemsets  length
91   0.074835  (whole milk, other vegetables)       2
103  0.056634        (whole milk, rolls/buns)       2
119  0.056024            (yogurt, whole milk)       2

## 7. Find all frequent itemsets of length 2 with minimum support of 2%?

In [27]:
frequent_itemsets[(frequent_itemsets['length'] == 2) & 
                  (frequent_itemsets['support'] >= 0.02)]

      support                             itemsets  length
91   0.074835       (whole milk, other vegetables)       2
103  0.056634             (whole milk, rolls/buns)       2
119  0.056024                 (yogurt, whole milk)       2
106  0.048907        (root vegetables, whole milk)       2
85   0.047382  (root vegetables, other vegetables)       2
..        ...                                  ...     ...
75   0.020539            (whole milk, frankfurter)       2
60   0.020437           (whole milk, bottled beer)       2
76   0.020437      (whole milk, frozen vegetables)       2
96   0.020437          (tropical fruit, pip fruit)       2
67   0.020031           (butter, other vegetables)       2

[61 rows x 3 columns]

## 8. Find the top 10 association rules with minimum support of 2%, sorted by confidence in descending order ?

In [28]:
rules = association_rules(frequent_itemsets, metric='support', min_threshold=0.02)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(whole milk),(other vegetables),0.255516,0.193493,0.074835,0.292877,1.513634,0.025394,1.140548
1,(other vegetables),(whole milk),0.193493,0.255516,0.074835,0.386758,1.513634,0.025394,1.214013
2,(whole milk),(rolls/buns),0.255516,0.183935,0.056634,0.221647,1.205032,0.009636,1.048452
3,(rolls/buns),(whole milk),0.183935,0.255516,0.056634,0.307905,1.205032,0.009636,1.075696
4,(yogurt),(whole milk),0.139502,0.255516,0.056024,0.401603,1.571735,0.020379,1.244132
...,...,...,...,...,...,...,...,...,...
129,(frozen vegetables),(whole milk),0.048094,0.255516,0.020437,0.424947,1.663094,0.008149,1.294636
130,(tropical fruit),(pip fruit),0.104931,0.075648,0.020437,0.194767,2.574648,0.012499,1.147931
131,(pip fruit),(tropical fruit),0.075648,0.104931,0.020437,0.270161,2.574648,0.012499,1.226392
132,(butter),(other vegetables),0.055414,0.193493,0.020031,0.361468,1.868122,0.009308,1.263065
133,(other vegetables),(butter),0.193493,0.055414,0.020031,0.103521,1.868122,0.009308,1.053661

## sorting the rules in the descending order by confidence

In [29]:
rules.sort_values(by='confidence', ascending=False)[0:10]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
97,"(yogurt, other vegetables)",(whole milk),0.043416,0.255516,0.022267,0.512881,2.007235,0.011174,1.528340
50,(butter),(whole milk),0.055414,0.255516,0.027555,0.497248,1.946053,0.013395,1.480817
61,(curd),(whole milk),0.053279,0.255516,0.026131,0.490458,1.919481,0.012517,1.461085
86,"(root vegetables, other vegetables)",(whole milk),0.047382,0.255516,0.023183,0.489270,1.914833,0.011076,1.457687
87,"(root vegetables, whole milk)",(other vegetables),0.048907,0.193493,0.023183,0.474012,2.449770,0.013719,1.533320
39,(domestic eggs),(whole milk),0.063447,0.255516,0.029995,0.472756,1.850203,0.013783,1.412030
30,(whipped/sour cream),(whole milk),0.071683,0.255516,0.032232,0.449645,1.759754,0.013916,1.352735
6,(root vegetables),(whole milk),0.108998,0.255516,0.048907,0.448694,1.756031,0.021056,1.350401
8,(root vegetables),(other vegetables),0.108998,0.193493,0.047382,0.434701,2.246605,0.026291,1.426693
129,(frozen vegetables),(whole milk),0.048094,0.255516,0.020437,0.424947,1.663094,0.008149,1.294636

## 9. Find association rules with minimum support of 2% and lift of more than 1.0 ?

In [30]:
rules[(rules['support'] >= 0.02) &
      (rules['lift'] > 1.0)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(whole milk),(other vegetables),0.255516,0.193493,0.074835,0.292877,1.513634,0.025394,1.140548
1,(other vegetables),(whole milk),0.193493,0.255516,0.074835,0.386758,1.513634,0.025394,1.214013
2,(whole milk),(rolls/buns),0.255516,0.183935,0.056634,0.221647,1.205032,0.009636,1.048452
3,(rolls/buns),(whole milk),0.183935,0.255516,0.056634,0.307905,1.205032,0.009636,1.075696
4,(yogurt),(whole milk),0.139502,0.255516,0.056024,0.401603,1.571735,0.020379,1.244132
...,...,...,...,...,...,...,...,...,...
129,(frozen vegetables),(whole milk),0.048094,0.255516,0.020437,0.424947,1.663094,0.008149,1.294636
130,(tropical fruit),(pip fruit),0.104931,0.075648,0.020437,0.194767,2.574648,0.012499,1.147931
131,(pip fruit),(tropical fruit),0.075648,0.104931,0.020437,0.270161,2.574648,0.012499,1.226392
132,(butter),(other vegetables),0.055414,0.193493,0.020031,0.361468,1.868122,0.009308,1.263065
133,(other vegetables),(butter),0.193493,0.055414,0.020031,0.103521,1.868122,0.009308,1.053661